### ISSUE TITLE
[Feature request] Add dynamic total depending on full boxes

### ISSUE THREAD

**Issue by antil0pa** [foodcoop-adam/foodsoft#179]
It will be really useful to see how much one will need to pay according to which boxes are full. So not-yet-full boxes will not count in the total and tolerance that fills up a box will be. 

At any given moment users could estimate how much they will need to pay and based on that they can decide if they can order more in order to fill another box.

**Comment by wvengen** [comment]
Thanks for your feature-request!
Do you have an idea for the user-interface?
In general, foodcoops try to get the boxes as full as possible, as to avoid disappointment. Do you think this is still relevant in light of that? Or does your coop work differently?

**Comment by antil0pa** [comment]
In our case, we are still very small and not every box can be completed. We do our best, but still the computed total that shows while ordering doesn't reflect what would be ordered at the end. Also the tolerance is not computed which makes it hard to estimate how much over (or below) budget you still are.
As for the interface - I can imagine two totals - either at the bottom of the order or on the left - under the computed total that is already there there could be a 'dynamic total' or 'what you actually will get total' :P I'm not so sure how to title it..

**Comment by wvengen** [comment]
Ah, thanks for explaining. I can see this being important for a starting foodcoop.
Regarding the interface, at the bottom of the order and on the left would both work I think. How to display this is still something to think about. It could be something like

```
Total     50.60
          (now 30.40)
```

with the text between brackets slightly grey/smaller and with a tooltip explaining the numbers. Something like _when the order would close now, the total would be 30.40 / if all boxes would be filled, the total would become 70.80_. 

This really could use a well-wrought explanation.
If we display the 'current' total here, as a user I'd expect to be able to see how the numbers above that add up. So that means it would be helpful to somehow show the current amounts + prices too.
But perhaps we can leave that for now, and focus on the total only (if we design well).

I'm thinking of using more progress-like-bars, e.g. below the quantity and tolerance to show how much of it will be used currently by the member. Expanding this idea, we could also add some progress-bar-like thing to prices, to visually show how far the current situation approaches the ideal (when all remaining boxes are filled). Some mockups:

![quantity_bar](https://cloud.githubusercontent.com/assets/503804/14967523/1d5a7a44-10b8-11e6-9a40-f702a56ed040.png)

![price_bar](https://cloud.githubusercontent.com/assets/503804/14967648/baa7998a-10b8-11e6-951f-5bb8ab3ea99f.png)

Or perhaps an effect on hover that expands the _My current order_ box at the left to show the minimum, current, and maximum amount. Just some ideas to get it flowing.

**Comment by antil0pa** [comment]
Nice mockups. 
I like both ideas - having the total below with the 'current total' in brackets for a quick visual view + having the _My current order_ box expanding with more information about the current total.

Having progress bars under quantity and tolerance are visually powerful, but should probably be accompanied with a tooltip explanation that reads something like _currently receiving 2 out of 4_

Another thing I'm wondering about is the fact the prices of the tolerance is not computed when it is used to fill a box. So maybe the tooltip hover effect can be used over the price where it can say _currently receiving 2+1, 12.66_ - where 2 is quantity, 1 tolerance and 12.66 the price of 3 units.

**Comment by wvengen** [comment]
The focus of this fork has become getting relevant functionality upstream. If you need this feature, please open an issue with [upstream foodsoft](https://github.com/foodcoops/foodsoft/issues).
