### ISSUE TITLE
Become member on the spot [@pickup moment] 

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#42]
at the moment interested people can become order by public signup and ideal. but people who do not know how to pay with ideal would like to become a member and pay with PIN

add "Add member" to admin menu bar
show "new member form" [potential member enters his information]
user is added + household (also called ordergroup)
35 euros is subtracted from account
To be paid with PIN transaction
go to "new member form" for next member

**Comment by wvengen** [comment]
implemented in branches rails3-selfsignup (create member+ordergroup at the same time) and foodcoop (checkbox for when member paid on the spot)

**Comment by Cor-Jan** [comment]
at the moment people who are filling in the membership form on the spot sometimes tick the checkbox without paying the 35 euros. 

is it that if someone becomes member and the 35 euro's are subtracted that by making a first transaction that puts the member out of negative balance the member has paid?
if not can we add a button to the member transaction screen when a members are not activated yet? (which is not there when paid?)

if so; is it an idea to delete the tickbox?

**Comment by wvengen** [comment]
This screen is meant to be used by administrators who enlist new members, not by members themself.
If we want new members to signup, then we'd better change the public_invite option: instead of sending an email with a link to signup, the user can fill in his details. This screen can then also be used at a public self-signup station.
This would require the addition of an email address verification function.

**Comment by wvengen** [comment]
To be revisited - users can use the rewritten signup feature on foodcoop-adam-new to signup. Then, on a different terminal/pc/laptop, they can pay the membership fee and their ordergroup will be activated.
