### ISSUE TITLE
[selfsignup] "pay membership fee" admin button

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#63]
as admin one can make people member by inserting their personal info and ticking a checkbox if this potential members has paid and to activate this household for ordering

in practice the membership form is filled in by the member itself and sometimes a member does check the checkbox without paying. 

how about we delete the checkbox below the orderform and create a button in the "manage accounts" screen to pay the membership fee and activate the member?

![screen shot 2013-05-29 at 1 42 14 pm](https://f.cloud.github.com/assets/3144698/578420/90e10df0-c856-11e2-9d54-965cef94d3c0.png)

linked to issue #61

**Comment by wvengen** [comment]
Creating a user from the admin screen **must** be done by an admin, not by a user himself. Users wanting to create an account can use the signup form.

A "pay membership" button would be useful.

**Comment by Cor-Jan** [comment]
practically: what does a admin has to do for creating a user in admin screen? type all the info in himself based on what the new members verbally tells him to? 
in my opinion that does not work. the admin version of the creating a user has in my opinion only 1 difference with public signup and that is that people can pay on the spot with for example PIN.
by deleting the activitate member checkbox, making members becomes a much more safe process and people can become a member fast.

i would suggest that after filling the admin membership form and clicking "OK" that a blank membership form appears so the next member can fill in their details.

**Comment by wvengen** [comment]
No. When an admin is logged in, another member should not use it - he or she can too easily mess up something (e.g., he thinks he's ordering for himself while he adds products to the admin's order). This functionality is meant for admins to do something for other users, e.g. when they have trouble to do that themselves. Or, for example, from a request by email. Exceptions, in our case, but the functionality needs to be there.

When people want to signup on the spot, a _different_ screen is needed. We've already talked about on the spot signup, where new members can use the signup screen on one computer, and on another computer an admin can then process their membership payment by PIN.

(This could be improved: after signing up, the user is now logged in - at on the spot signup, it may be best to have account details emailed, and returning to the signup screen so that a different user can signup.)

**Comment by Cor-Jan** [comment]
ah, than i understand what you mean. looking forward to on the spot adding
members functionality

**Comment by wvengen** [comment]
#42 for signing up new members on the spot
