### ISSUE TITLE
inform on order results (when all orders are closed for a specific pickup day)

### ISSUE THREAD

**Issue by Cor-Jan** [foodcoop-adam/foodsoft#68]
There is already a function in foodcoop to inform what order results are when orders are closed.

activate standard, add to settings
change that this notification is per total memberorder and not per supplier

**Comment by wvengen** [comment]
The notification function didn't work for single-coop installes, which was fixed by 36ed148a1239df4d1c0bc12fd183c21b2a1d1946. Then 36ed148a1239df4d1c0bc12fd183c21b2a1d1946 fixed the mail format. Now it should be possible to send mails when a supplier's order is closed.

Pending: send mail about all orders when all orders have been closed. Either that, or wait for multiple suppliers in single group_order functionality #82.
